import {z} from 'zod';
import type {Section} from './types';
export type FieldSpec={name:string;type?:string;optional?:boolean;relation?:string;options?:string[]};
const address:FieldSpec[]=['legalName','email','street','city','postalCode','country','vatId'].map(name=>({name,type:name==='email'?'email':'text'}));
export const formFields:Partial<Record<Section,FieldSpec[]>>={projects:[{name:'name'},{name:'key'}],customers:[{name:'userId',type:'number'},...address.map(f=>({...f,optional:f.name==='vatId'}))],settings:[...address,{name:'contactName'},{name:'phone',type:'tel'}],contributors:[{name:'name'},{name:'kind',options:['DEVELOPER','AFFILIATE','MARKETING','PROMOTER','MEDIA','EMPLOYEE','CONTRACTOR','INVESTOR']}],contracts:[{name:'projectId',relation:'projects'},{name:'contributorId',relation:'contributors'},{name:'number'},{name:'version',type:'number'},{name:'rate'},{name:'startsAt',type:'date'},{name:'endsAt',type:'date',optional:true}],expenses:[{name:'projectId',relation:'projects'},{name:'description'},{name:'amount'},{name:'classification',options:['FIXED','VARIABLE']},{name:'recurrence',options:['ONCE','MONTHLY','YEARLY']}],invoices:[{name:'projectId',relation:'projects'},{name:'customerId',relation:'customers'},{name:'buyerReference'},{name:'supplyDate',type:'date'},{name:'dueDate',type:'date'}]};
export function formSchema(section:Section){const shape:Record<string,z.ZodType>={};for(const f of formFields[section]??[]){shape[f.name]=f.optional?z.string().optional():f.type==='email'?z.email():f.type==='date'?z.iso.date():z.string().min(1);}if(section==='invoices'){shape.lines=z.array(z.object({description:z.string().min(1),quantity:z.string().min(1),unitPrice:z.string().min(1),vatRate:z.string().min(1)})).min(1);shape.contractIds=z.array(z.string()).default([]);}return z.object(shape);}
export function payload(section:Section,raw:Record<string,unknown>,locale:string){const values={...raw} as Record<string,any>;const normalize=(v:string)=>v.replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[٫,]/g,'.');for(const k of ['userId','version','rate','amount'])if(values[k])values[k]=normalize(values[k]);if(section==='customers'||section==='settings'){values.address=Object.fromEntries(['street','city','postalCode','country'].map(k=>[k,values[k]]));values.address.country=values.address.country.toUpperCase();for(const k of ['street','city','postalCode','country'])delete values[k];if(section==='customers'){values.userId=Number(values.userId);values.locale=locale;if(!values.vatId)delete values.vatId;}}
if(section==='contracts'){values.version=Number(values.version);values.basis='NET_SALES_BEFORE_FEES';values.startsAt=new Date(values.startsAt+'T00:00:00Z').toISOString();if(values.endsAt)values.endsAt=new Date(values.endsAt+'T23:59:59Z').toISOString();else delete values.endsAt;}
if(section==='expenses')values.currency='EUR';if(section==='invoices'){values.locale=locale;values.lines=values.lines.map((l:Record<string,string>)=>({...l,quantity:normalize(l.quantity),unitPrice:normalize(l.unitPrice),vatRate:normalize(l.vatRate)}));}return values;}
