import {useEffect} from 'react';
import {useForm,useFieldArray,type Resolver} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {useQueries} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {useNavigate} from 'react-router';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Field,FieldGroup,FieldLabel,FieldError} from '@/components/ui/field';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Spinner} from '@/components/ui/spinner';
import {Controller} from 'react-hook-form';
import {useCreateRecord} from '../../hooks/use-finance';
import {listRecords} from '../../api/finance-api';
import {formFields,formSchema,payload} from '../../model/schema';
import type {Section,FormValues,FinanceRecord} from '../../model/types';
export function RecordForm({section,initial}:{section:Section;initial?:Record<string,unknown>}){const {t,i18n}=useTranslation();const navigate=useNavigate();const mutation=useCreateRecord(section);const fields=formFields[section]??[];const names=[...new Set(fields.flatMap(f=>f.relation?[f.relation]:[])),...(section==='invoices'?['contracts']:[])];const lookups=useQueries({queries:names.map(name=>({queryKey:['finance',name,i18n.language],queryFn:()=>listRecords(name as Section,i18n.language)}))});const form=useForm<FormValues>({resolver:zodResolver(formSchema(section)) as unknown as Resolver<FormValues>,defaultValues:{country:'DE',version:'1',startsAt:new Date().toISOString().slice(0,10),supplyDate:new Date().toISOString().slice(0,10),lines:[{description:'',quantity:'1',unitPrice:'',vatRate:'19'}],contractIds:[]}});useEffect(()=>{if(initial)form.reset({...form.getValues(),...initial,...(initial.address as object??{})} as FormValues);},[initial]);const lines=useFieldArray({control:form.control,name:'lines'});const project=form.watch('projectId');const selected=form.watch('contractIds')??[];useEffect(()=>{form.setValue('contractIds',[]);},[project]);const lookup=(name:string):FinanceRecord[]=>lookups[names.indexOf(name)]?.data??[];return <form onSubmit={form.handleSubmit(values=>mutation.mutate(payload(section,values,i18n.language),{onSuccess:()=>navigate(`/finance/${section}`)}))}><FieldGroup className="gap-6"><FieldGroup className="grid grid-cols-1 gap-5 lg:grid-cols-3">{fields.map(spec=><Field key={spec.name}><FieldLabel htmlFor={spec.name}>{t(`finance.${spec.name}`)}</FieldLabel>{spec.options||spec.relation?<Controller control={form.control} name={spec.name} render={({field})=><Select value={typeof field.value==='string'?field.value:''} onValueChange={field.onChange}><SelectTrigger id={spec.name} className="w-full"><SelectValue placeholder={t('finance.select')}/></SelectTrigger><SelectContent>{spec.options?spec.options.map(value=><SelectItem key={value} value={value}>{t(`finance.enums.${value}`)}</SelectItem>):lookup(spec.relation!).map(item=><SelectItem key={item.id} value={item.id}>{item.name??item.legalName??item.number}</SelectItem>)}</SelectContent></Select>}/>:<Input id={spec.name} type={spec.type??'text'} {...form.register(spec.name)}/>}<FieldError>{form.formState.errors[spec.name]&&t('finance.invalid')}</FieldError></Field>)}</FieldGroup>
{section==='contracts'&&<p className="text-muted-foreground text-sm">{t('finance.basis')}</p>}{section==='invoices'&&<><p className="text-muted-foreground text-sm">{t('finance.scope')}</p><Field><FieldLabel>{t('finance.contracts')}</FieldLabel>{lookup('contracts').filter(c=>c.projectId===project).map(c=><label className="flex gap-3 items-center" key={c.id}><Checkbox checked={selected.includes(c.id)} onCheckedChange={checked=>form.setValue('contractIds',checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/>{c.contributor?.name} · {c.number} · {c.rate}%</label>)}</Field>{lines.fields.map((line,index)=><FieldGroup key={line.id} className="grid grid-cols-1 gap-4 md:grid-cols-5">{(['description','quantity','unitPrice','vatRate'] as const).map(key=><Field key={key}><FieldLabel htmlFor={`${key}-${index}`}>{t(`finance.${key}`)}</FieldLabel><Input id={`${key}-${index}`} {...form.register(`lines.${index}.${key}`)}/><FieldError>{form.formState.errors.lines?.[index]?.[key]&&t('finance.invalid')}</FieldError></Field>)}<Button variant="outline" type="button" className="self-end" disabled={lines.fields.length===1} onClick={()=>lines.remove(index)}>{t('finance.remove')}</Button></FieldGroup>)}<Button variant="outline" type="button" className="self-start" onClick={()=>lines.append({description:'',quantity:'1',unitPrice:'',vatRate:'19'})}>{t('finance.addLine')}</Button></>}
{(mutation.error||lookups.some(q=>q.error))&&<p role="alert" className="text-destructive">{mutation.error?.message??lookups.find(q=>q.error)?.error?.message}</p>}<Field orientation="horizontal" className="justify-end gap-2"><Button variant="outline" type="button" onClick={()=>navigate(`/finance/${section}`)}>{t('finance.cancel')}</Button><Button disabled={mutation.isPending||lookups.some(q=>q.isPending)}>{t('finance.save')}{mutation.isPending&&<Spinner/>}</Button></Field></FieldGroup></form>;}
